/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TourIdRouteImport } from './routes/tour.$id'
import { Route as AdminToursRouteImport } from './routes/admin.tours'

const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourIdRoute = TourIdRouteImport.update({
  id: '/tour/$id',
  path: '/tour/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToursRoute = AdminToursRouteImport.update({
  id: '/admin/tours',
  path: '/admin/tours',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/tours': typeof ToursRoute
  '/admin/tours': typeof AdminToursRoute
  '/tour/$id': typeof TourIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/tours': typeof ToursRoute
  '/admin/tours': typeof AdminToursRoute
  '/tour/$id': typeof TourIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/tours': typeof ToursRoute
  '/admin/tours': typeof AdminToursRoute
  '/tour/$id': typeof TourIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/tours' | '/admin/tours' | '/tour/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/tours' | '/admin/tours' | '/tour/$id'
  id: '__root__' | '/' | '/contact' | '/tours' | '/admin/tours' | '/tour/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ToursRoute: typeof ToursRoute
  AdminToursRoute: typeof AdminToursRoute
  TourIdRoute: typeof TourIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$id': {
      id: '/tour/$id'
      path: '/tour/$id'
      fullPath: '/tour/$id'
      preLoaderRoute: typeof TourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tours': {
      id: '/admin/tours'
      path: '/admin/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AdminToursRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ToursRoute: ToursRoute,
  AdminToursRoute: AdminToursRoute,
  TourIdRoute: TourIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
